services:
  - type: web
    name: affiliate-platform-mern
    env: node
    region: oregon
    plan: free
    buildCommand: node build.js
    startCommand: node backend/server.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://affiliate-platform-mern.onrender.com
    autoDeploy: true
    branch: main
