services:
  - type: web
    name: affiliate-platform
    env: node
    buildCommand: npm run build
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true  # Render will generate a secure secret
